// ═══════════════════════════════════════════════════════════
// KAHRAMAN OPTİK — TOPLU IMPORT VERİSİ
// Bu dosya tüm Sanity dokümanlarının kaynağıdır.
// ═══════════════════════════════════════════════════════════

// ─── Yardımcı: Düz metin → Sanity Portable Text (paragraf) ───
const toBlock = (text) => ({
  _type: 'block',
  style: 'normal',
  children: [{_type: 'span', text, marks: []}],
  markDefs: [],
})

// ─── Yardımcı: Tech specs objesi → Sanity array formatı ───
const toSpecs = (obj) => Object.entries(obj).map(([label, value], i) => ({
  _key: `spec-${i}`,
  _type: 'object',
  label,
  value,
}))

// ═══════════════════════════════════════════════════════════
// ÜRÜNLER (9 adet: 6 mevcut + 3 sarf malzemesi)
// ═══════════════════════════════════════════════════════════

export const products = [
  // ──────────── CNC KESİM (3 ürün) ────────────
  {
    _id: 'product-ko-cnc-500x',
    _type: 'product',
    name: 'KO-CNC 500X',
    slug: {_type: 'slug', current: 'ko-cnc-500x'},
    category: 'cnc-kesim',
    displayOrder: 1,
    shortDescriptionTR: 'Yüksek hassasiyetli endüstriyel kesim.',
    shortDescriptionEN: 'High-precision industrial cutting.',
    taglineTR: 'Endüstri 4.0 standartlarında çalışan referans modelimiz.',
    taglineEN: 'Our reference model, built for Industry 4.0 standards.',
    longDescriptionTR: [
      toBlock('KO-CNC 500X, gözlük üretimi için tasarlanmış orta ölçekli üretim hatlarının referans modelidir. 500×500 mm çalışma sahasında ±0.01 mm hassasiyetle çalışır; kapalı çevrim servo sistemler, yüksek frekans çekirdek ve aktif titreşim sönümleme ile uzun süreli üretim sürekliliği sağlar.'),
      toBlock('Sistem; otomatik kalibrasyon, lazerli sıfır referansı ve operatör müdahalesi gerektirmeyen takım değişimi ile donatılmıştır. Sahada beş yılı aşkın süredir görev yapan birimler; 24/7 vardiya rutininde MTBF değerini yüksek tutar.'),
      toBlock('Türkiye genelindeki yetkili servis ağı sayesinde olası bir arıza durumunda yerinde müdahale ortalama 24 saat içinde tamamlanır. Tüm yeni sistemlerde 2 yıl garanti standart olarak verilir.'),
    ],
    longDescriptionEN: [
      toBlock('The KO-CNC 500X is our reference model for mid-scale eyewear production lines. It operates with ±0.01 mm precision across a 500×500 mm work envelope, with closed-loop servo systems, a high-frequency spindle and active vibration damping ensuring extended production continuity.'),
      toBlock('The system ships with automatic calibration, laser-based zero referencing and tool changes that require no operator intervention. Units running in the field for over five years maintain a high MTBF on 24/7 shift schedules.'),
      toBlock('Through our nationwide authorised service network, on-site response is typically completed within 24 hours. A standard 2-year warranty is included with every new system.'),
    ],
    keySpecs: ['±0.01mm', '500×500mm', '3.5kW'],
    techSpecsTR: toSpecs({
      'Kesim Boyutu': '500 × 500 mm',
      'Hassasiyet': '±0.01 mm',
      'Motor Gücü': '3.5 kW',
      'Hız / Devir': '15.000 RPM',
      'Boyutlar': '1200 × 800 × 1600 mm',
      'Ağırlık': '450 kg',
      'Elektrik': '380V / 50Hz / 3 faz',
      'Garanti': '2 yıl',
      'Üretim Yılı': '2024',
    }),
    techSpecsEN: toSpecs({
      'Cutting Size': '500 × 500 mm',
      'Precision': '±0.01 mm',
      'Motor Power': '3.5 kW',
      'Speed / RPM': '15,000 RPM',
      'Dimensions': '1200 × 800 × 1600 mm',
      'Weight': '450 kg',
      'Electrical': '380V / 50Hz / 3 phase',
      'Warranty': '2 years',
      'Year': '2024',
    }),
    showPrice: false,
    monthlyViews: 47,
    isActive: true,
    isFeatured: true,
    isNew: false,
  },
  {
    _id: 'product-ko-cnc-800x',
    _type: 'product',
    name: 'KO-CNC 800X',
    slug: {_type: 'slug', current: 'ko-cnc-800x'},
    category: 'cnc-kesim',
    displayOrder: 2,
    shortDescriptionTR: 'Geniş tabla, yüksek hacimli üretim hattı.',
    shortDescriptionEN: 'Wide-bed, high-volume production line.',
    taglineTR: 'Seri üretim odaklı geniş çalışma sahası.',
    taglineEN: 'Wide work envelope for serial production.',
    longDescriptionTR: [
      toBlock('KO-CNC 800X, ihracat odaklı orta-büyük ölçekli üreticiler için tasarlanmıştır. 800×600 mm tablası ile tek seansta birden fazla iş parçası işlenebilir; çift palet sistemi sayesinde çevrim süreleri %30 oranında düşürülür.'),
      toBlock('Yüksek momentli ana mil ve doğrusal kılavuz sistemleri, ağır kesim koşullarında dahi yüksek tekrarlanabilirlik sağlar. Entegre MES bağlantısı ile üretim verileri gerçek zamanlı izlenir.'),
      toBlock('Standart paket; otomatik takım değiştirici, koruma kabini ve aspirasyon ünitesini içerir.'),
    ],
    longDescriptionEN: [
      toBlock('The KO-CNC 800X is built for export-oriented medium-to-large manufacturers. Its 800×600 mm bed lets multiple workpieces be machined per cycle; a dual-pallet system cuts cycle times by 30%.'),
      toBlock('A high-torque spindle and linear guideways maintain high repeatability even under heavy cutting loads. Integrated MES connectivity streams production data in real time.'),
      toBlock('The standard package includes an automatic tool changer, enclosed guarding and a dust-extraction unit.'),
    ],
    keySpecs: ['±0.015mm', '800×600mm', '5.5kW'],
    techSpecsTR: toSpecs({
      'Kesim Boyutu': '800 × 600 mm',
      'Hassasiyet': '±0.015 mm',
      'Motor Gücü': '5.5 kW',
      'Hız / Devir': '18.000 RPM',
      'Boyutlar': '1800 × 1100 × 1900 mm',
      'Ağırlık': '780 kg',
      'Elektrik': '380V / 50Hz / 3 faz',
      'Garanti': '2 yıl',
      'Üretim Yılı': '2025',
    }),
    techSpecsEN: toSpecs({
      'Cutting Size': '800 × 600 mm',
      'Precision': '±0.015 mm',
      'Motor Power': '5.5 kW',
      'Speed / RPM': '18,000 RPM',
      'Dimensions': '1800 × 1100 × 1900 mm',
      'Weight': '780 kg',
      'Electrical': '380V / 50Hz / 3 phase',
      'Warranty': '2 years',
      'Year': '2025',
    }),
    showPrice: false,
    monthlyViews: 62,
    isActive: true,
    isFeatured: false,
    isNew: true,
  },
  {
    _id: 'product-ko-cnc-320',
    _type: 'product',
    name: 'KO-CNC 320 Mini',
    slug: {_type: 'slug', current: 'ko-cnc-320-mini'},
    category: 'cnc-kesim',
    displayOrder: 3,
    shortDescriptionTR: 'Atölye tipi prototipleme ve numune üretimi.',
    shortDescriptionEN: 'Workshop prototyping and sample runs.',
    taglineTR: 'Küçük seri üretim ve numune işleme için kompakt çözüm.',
    taglineEN: 'A compact unit for small-batch and prototype work.',
    longDescriptionTR: [
      toBlock('KO-CNC 320 Mini, atölye ölçeğinde prototipleme ve düşük hacimli üretim için optimize edilmiştir. 320×320 mm çalışma sahasında yüksek hassasiyet korunurken cihaz, standart 220V hatta bağlanabilir.'),
      toBlock('Kompakt gövde sayesinde mevcut bir üretim hattının ek istasyonu olarak da konumlandırılabilir. Operatör öğrenme eğrisi düşüktür; eğitim ortalama yarım gün sürer.'),
      toBlock('Tüm ölçüm cihazlarımız ile uyumlu olan ortak ara yüz, hat genelinde tutarlı raporlama sağlar.'),
    ],
    longDescriptionEN: [
      toBlock('The KO-CNC 320 Mini is optimised for workshop-scale prototyping and low-volume production. It maintains high precision across a 320×320 mm work envelope and runs from a standard 220V supply.'),
      toBlock('Its compact footprint also positions it well as a satellite station next to an existing line. The operator learning curve is short — training averages half a day.'),
      toBlock('A shared interface compatible with all our measurement devices keeps reporting consistent across the line.'),
    ],
    keySpecs: ['±0.01mm', '320×320mm', '1.5kW'],
    techSpecsTR: toSpecs({
      'Kesim Boyutu': '320 × 320 mm',
      'Hassasiyet': '±0.01 mm',
      'Motor Gücü': '1.5 kW',
      'Hız / Devir': '12.000 RPM',
      'Boyutlar': '900 × 700 × 1400 mm',
      'Ağırlık': '210 kg',
      'Elektrik': '220V / 50Hz / 1 faz',
      'Garanti': '18 ay',
      'Üretim Yılı': '2024',
    }),
    techSpecsEN: toSpecs({
      'Cutting Size': '320 × 320 mm',
      'Precision': '±0.01 mm',
      'Motor Power': '1.5 kW',
      'Speed / RPM': '12,000 RPM',
      'Dimensions': '900 × 700 × 1400 mm',
      'Weight': '210 kg',
      'Electrical': '220V / 50Hz / 1 phase',
      'Warranty': '18 months',
      'Year': '2024',
    }),
    showPrice: false,
    monthlyViews: 28,
    isActive: true,
    isFeatured: false,
    isNew: false,
  },

  // ──────────── ÖLÇÜM CİHAZI (3 ürün) ────────────
  {
    _id: 'product-ko-optic-v2',
    _type: 'product',
    name: 'KO-Optic V2',
    slug: {_type: 'slug', current: 'ko-optic-v2'},
    category: 'olcum',
    displayOrder: 4,
    shortDescriptionTR: 'Otomatik lensometre, hat üzeri kalite kontrol.',
    shortDescriptionEN: 'Automatic lensmeter for inline QC.',
    taglineTR: 'Üretim sonu hızlı doğrulama için tek dokunuş.',
    taglineEN: 'One-touch end-of-line verification.',
    longDescriptionTR: [
      toBlock('KO-Optic V2, üretim hattı sonunda kalite kontrol için tasarlanmış otomatik lensometredir. Tek dokunuşla dioptri, prizma ve UV ölçümü 2 saniye altında tamamlanır.'),
      toBlock('Otomatik kalibrasyon ile günlük servis ihtiyacı ortadan kalkar. USB-C üzerinden anlık veri aktarımı yapılabilir; üretim takip yazılımlarına standart bir adaptörle entegre olur.'),
      toBlock('KO-CNC serisi makinelerin üretim çıktısını doğrulamak için referans cihaz olarak kullanılır.'),
    ],
    longDescriptionEN: [
      toBlock('The KO-Optic V2 is an automated lensmeter designed for end-of-line QC. Diopter, prism and UV measurement complete in under 2 seconds with a single touch.'),
      toBlock('Automatic calibration removes the need for daily servicing. Real-time data export over USB-C plugs into existing production-tracking software via a standard adapter.'),
      toBlock('It is the reference device used to validate output from the KO-CNC series of cutters.'),
    ],
    keySpecs: ['±0.01 D', 'UV ölçüm', 'USB-C'],
    techSpecsTR: toSpecs({
      'Ölçüm Aralığı': '±25 D',
      'Hassasiyet': '±0.01 D',
      'Motor Gücü': '40 W',
      'Hız / Devir': '< 2 sn / lens',
      'Boyutlar': '380 × 320 × 480 mm',
      'Ağırlık': '12 kg',
      'Elektrik': '220V / 50Hz / 1 faz',
      'Garanti': '2 yıl',
      'Üretim Yılı': '2024',
    }),
    techSpecsEN: toSpecs({
      'Range': '±25 D',
      'Precision': '±0.01 D',
      'Power': '40 W',
      'Speed': '< 2 s / lens',
      'Dimensions': '380 × 320 × 480 mm',
      'Weight': '12 kg',
      'Electrical': '220V / 50Hz / 1 phase',
      'Warranty': '2 years',
      'Year': '2024',
    }),
    showPrice: false,
    monthlyViews: 41,
    isActive: true,
    isFeatured: true,
    isNew: false,
  },
  {
    _id: 'product-ko-lens-pro',
    _type: 'product',
    name: 'KO-Lens Pro',
    slug: {_type: 'slug', current: 'ko-lens-pro'},
    category: 'olcum',
    displayOrder: 5,
    shortDescriptionTR: 'Yüksek hassasiyetli dioptri ve prizma analizi.',
    shortDescriptionEN: 'High-precision diopter and prism analysis.',
    taglineTR: 'Laboratuvar düzeyinde sertifika çıktısı.',
    taglineEN: 'Lab-grade certificate output.',
    longDescriptionTR: [
      toBlock('KO-Lens Pro, sertifikalı ölçüm çıktısı gerektiren üreticiler için tasarlanmıştır. 0.001 D çözünürlükte çalışır; her ölçüm için zaman damgalı PDF raporu üretir.'),
      toBlock('Otomatik programlama özelliği ile farklı lens tipleri arasında geçiş manuel müdahale gerektirmez. Hat verisi MES ve ERP sistemlerine REST API ile entegre olur.'),
      toBlock('Akredite test laboratuvarları ve ihracat odaklı üreticiler için referans cihaz konumundadır.'),
    ],
    longDescriptionEN: [
      toBlock('The KO-Lens Pro is designed for manufacturers that need certified measurement output. It operates at 0.001 D resolution and produces a time-stamped PDF report for every measurement.'),
      toBlock('Auto-programming switches between lens types with no manual intervention. Line data integrates with MES and ERP systems over a REST API.'),
      toBlock('It is the reference device for accredited test labs and export-focused manufacturers.'),
    ],
    keySpecs: ['0.001 D', 'Auto-prog', 'PDF rapor'],
    techSpecsTR: toSpecs({
      'Ölçüm Aralığı': '±35 D',
      'Hassasiyet': '±0.005 D',
      'Çözünürlük': '0.001 D',
      'Motor Gücü': '60 W',
      'Hız / Devir': '< 1.5 sn / lens',
      'Boyutlar': '420 × 360 × 520 mm',
      'Ağırlık': '15 kg',
      'Elektrik': '220V / 50Hz / 1 faz',
      'Garanti': '2 yıl',
      'Üretim Yılı': '2025',
    }),
    techSpecsEN: toSpecs({
      'Range': '±35 D',
      'Precision': '±0.005 D',
      'Resolution': '0.001 D',
      'Power': '60 W',
      'Speed': '< 1.5 s / lens',
      'Dimensions': '420 × 360 × 520 mm',
      'Weight': '15 kg',
      'Electrical': '220V / 50Hz / 1 phase',
      'Warranty': '2 years',
      'Year': '2025',
    }),
    showPrice: false,
    monthlyViews: 33,
    isActive: true,
    isFeatured: false,
    isNew: true,
  },
  {
    _id: 'product-ko-vision-bench',
    _type: 'product',
    name: 'KO-Vision Bench',
    slug: {_type: 'slug', current: 'ko-vision-bench'},
    category: 'olcum',
    displayOrder: 6,
    shortDescriptionTR: 'Ar-Ge ve referans ölçüm istasyonu.',
    shortDescriptionEN: 'R&D and reference measurement station.',
    taglineTR: 'Mikron mertebesinde optik tezgah.',
    taglineEN: 'Optical bench at micron-level precision.',
    longDescriptionTR: [
      toBlock('KO-Vision Bench, üretim hattınızı sertifikalandırmak için bir referans cihazıdır. Çift kameralı görüntü işleme sistemi ve granit gövdesi sayesinde mikron seviyesinde tekrarlanabilirlik sağlar.'),
      toBlock('Ar-Ge ekipleri için yeni lens tasarımlarının doğrulanması, üretim ekipleri için ise hat ekipmanlarının periyodik denetimi konularında en yüksek hassasiyeti sunar.'),
      toBlock('Üç yıl garanti ile teslim edilir; izlenebilirlik ve kalibrasyon raporları otomatik üretilir.'),
    ],
    longDescriptionEN: [
      toBlock('The KO-Vision Bench is a reference device for certifying your production line. A dual-camera vision system on a granite base delivers micron-level repeatability.'),
      toBlock('It serves R&D teams validating new lens designs and production teams running periodic audits of line equipment at the highest precision tier.'),
      toBlock('Shipped with a 3-year warranty; traceability and calibration reports are generated automatically.'),
    ],
    keySpecs: ['0.5 µm', 'Çift kamera', 'Granit gövde'],
    techSpecsTR: toSpecs({
      'Tabla Boyutu': '900 × 600 mm',
      'Hassasiyet': '±0.005 mm',
      'Çözünürlük': '0.5 µm',
      'Motor Gücü': '80 W',
      'Boyutlar': '1100 × 800 × 1300 mm',
      'Ağırlık': '320 kg',
      'Elektrik': '220V / 50Hz / 1 faz',
      'Garanti': '3 yıl',
      'Üretim Yılı': '2025',
    }),
    techSpecsEN: toSpecs({
      'Bed Size': '900 × 600 mm',
      'Precision': '±0.005 mm',
      'Resolution': '0.5 µm',
      'Power': '80 W',
      'Dimensions': '1100 × 800 × 1300 mm',
      'Weight': '320 kg',
      'Electrical': '220V / 50Hz / 1 phase',
      'Warranty': '3 years',
      'Year': '2025',
    }),
    showPrice: false,
    monthlyViews: 19,
    isActive: true,
    isFeatured: false,
    isNew: false,
  },

  // ──────────── SARF MALZEMELERİ (3 ürün) ────────────
  {
    _id: 'product-parlatma-sivisi-x50',
    _type: 'product',
    name: 'Optik Cam Parlatma Sıvısı X-50',
    slug: {_type: 'slug', current: 'optik-cam-parlatma-sivisi-x50'},
    category: 'sarf',
    displayOrder: 7,
    shortDescriptionTR: 'CR-39 ve polikarbonat lensler için yüzey parlatma sıvısı.',
    shortDescriptionEN: 'Surface polishing fluid for CR-39 and polycarbonate lenses.',
    taglineTR: 'Hat sonu parlatma için endüstriyel formül.',
    taglineEN: 'Industrial-grade formula for end-of-line polishing.',
    longDescriptionTR: [
      toBlock('X-50 parlatma sıvısı, optik cam kesim sonrasında yüzey pürüzsüzlüğünü artırmak için tasarlanmıştır. CR-39, polikarbonat ve yüksek indeksli lenslerde tutarlı sonuç verir.'),
      toBlock('Asit içermez, korozif değildir, üretim hattı ekipmanlarına zarar vermez. Otomatik dozajlama sistemleriyle uyumludur.'),
      toBlock('Toplu satın alımlarda fiyat indirimi mevcuttur. MSDS (Güvenlik Bilgi Formu) PDF olarak ürün sayfasında yer alır.'),
    ],
    longDescriptionEN: [
      toBlock('X-50 polishing fluid is designed to enhance surface smoothness after optical lens cutting. It provides consistent results on CR-39, polycarbonate and high-index lenses.'),
      toBlock('Acid-free, non-corrosive, safe for production line equipment. Compatible with automatic dosing systems.'),
      toBlock('Bulk purchase discounts available. MSDS (Material Safety Data Sheet) is provided as a PDF on the product page.'),
    ],
    keySpecs: ['5 L', 'pH 7.2', 'Asit içermez'],
    techSpecsTR: toSpecs({
      'Hacim': '5 Litre',
      'pH Değeri': '7.2 (nötr)',
      'Renk': 'Şeffaf',
      'Yoğunluk': '1.05 g/mL',
      'Saklama Sıcaklığı': '5 – 30 °C',
      'Raf Ömrü': '24 ay',
      'Ambalaj': 'HDPE bidon',
      'Sertifika': 'ISO 9001',
    }),
    techSpecsEN: toSpecs({
      'Volume': '5 Liters',
      'pH Value': '7.2 (neutral)',
      'Color': 'Transparent',
      'Density': '1.05 g/mL',
      'Storage Temp': '5 – 30 °C',
      'Shelf Life': '24 months',
      'Packaging': 'HDPE drum',
      'Certificate': 'ISO 9001',
    }),
    showPrice: true,
    price: 850,
    priceCurrency: 'TRY',
    priceNote: '+ KDV, kargo hariç',
    monthlyViews: 12,
    isActive: true,
    isFeatured: false,
    isNew: true,
  },
  {
    _id: 'product-elmas-bicak-3mm',
    _type: 'product',
    name: 'Elmas Uçlu CNC Bıçağı (3mm)',
    slug: {_type: 'slug', current: 'elmas-uclu-cnc-bicagi-3mm'},
    category: 'sarf',
    displayOrder: 8,
    shortDescriptionTR: 'KO-CNC serisi için orijinal kesim bıçağı.',
    shortDescriptionEN: 'Original cutting blade for KO-CNC series.',
    taglineTR: 'Uzun ömürlü elmas kaplama, yüksek devir uyumlu.',
    taglineEN: 'Long-life diamond coating, high-RPM compatible.',
    longDescriptionTR: [
      toBlock('Elmas uçlu CNC bıçağı, KO-CNC 500X ve KO-CNC 800X modelleri için orijinal sarf parçasıdır. Optik cam kesiminde 200 saate kadar performansını korur.'),
      toBlock('Yüksek devir koşullarında (15.000 - 18.000 RPM) titreşim yapmaz. Standart kovan boyutu sayesinde takım değiştirici uyumludur.'),
      toBlock('Toplu siparişlerde teslim süresi 5-7 iş günüdür. 10 adet ve üzeri alımlarda %10 indirim uygulanır.'),
    ],
    longDescriptionEN: [
      toBlock('The diamond-tipped CNC blade is the original consumable for KO-CNC 500X and KO-CNC 800X models. It maintains performance for up to 200 hours of optical glass cutting.'),
      toBlock('Vibration-free under high-RPM conditions (15,000 - 18,000 RPM). Standard collet size ensures compatibility with the automatic tool changer.'),
      toBlock('Bulk orders ship within 5-7 business days. 10% discount applies to orders of 10 units or more.'),
    ],
    keySpecs: ['3mm', '200 saat ömür', 'Elmas kaplama'],
    techSpecsTR: toSpecs({
      'Çap': '3 mm',
      'Uç Malzemesi': 'Elmas kaplama',
      'Maks. Devir': '20.000 RPM',
      'Tahmini Ömür': '200 saat',
      'Kovan Boyutu': 'ER11 standart',
      'Uyumlu Modeller': 'KO-CNC 500X, KO-CNC 800X',
      'Garanti': 'Üretim hatasına karşı',
    }),
    techSpecsEN: toSpecs({
      'Diameter': '3 mm',
      'Tip Material': 'Diamond coating',
      'Max RPM': '20,000 RPM',
      'Estimated Life': '200 hours',
      'Collet Size': 'ER11 standard',
      'Compatible Models': 'KO-CNC 500X, KO-CNC 800X',
      'Warranty': 'Against manufacturing defects',
    }),
    showPrice: true,
    price: 1250,
    priceCurrency: 'TRY',
    priceNote: '+ KDV, adet fiyatıdır',
    monthlyViews: 18,
    isActive: true,
    isFeatured: false,
    isNew: false,
  },
  {
    _id: 'product-kalibrasyon-lens-seti',
    _type: 'product',
    name: 'Kalibrasyon Test Lensi Seti',
    slug: {_type: 'slug', current: 'kalibrasyon-test-lensi-seti'},
    category: 'sarf',
    displayOrder: 9,
    shortDescriptionTR: 'KO-Lens Pro ve KO-Optic V2 için referans set.',
    shortDescriptionEN: 'Reference set for KO-Lens Pro and KO-Optic V2.',
    taglineTR: 'Ölçüm cihazlarınızın doğruluğunu garanti altına alın.',
    taglineEN: 'Guarantee the accuracy of your measurement devices.',
    longDescriptionTR: [
      toBlock('Bu set, ölçüm cihazlarımızın periyodik kalibrasyonu için 6 adet sertifikalı referans lensten oluşur. Her lens, ulusal kalibrasyon enstitüsü onaylıdır ve izlenebilirlik belgesiyle teslim edilir.'),
      toBlock('Önerilen kalibrasyon sıklığı 6 ayda birdir. Akredite laboratuvarlar için 3 aylık döngü tavsiye edilir.'),
      toBlock('Set; -10 D, -5 D, 0 D, +5 D, +10 D ve +15 D değerlerinde lensleri içerir. Saklama kutusu ve temizlik kiti pakette yer alır.'),
    ],
    longDescriptionEN: [
      toBlock('This set contains 6 certified reference lenses for periodic calibration of our measurement devices. Each lens is approved by a national calibration institute and ships with a traceability certificate.'),
      toBlock('Recommended calibration frequency is every 6 months. A 3-month cycle is recommended for accredited laboratories.'),
      toBlock('The set includes lenses at -10 D, -5 D, 0 D, +5 D, +10 D and +15 D. A storage case and cleaning kit are included in the package.'),
    ],
    keySpecs: ['6 lens', '±0.001 D', 'Sertifikalı'],
    techSpecsTR: toSpecs({
      'Lens Sayısı': '6 adet',
      'Dioptri Değerleri': '-10, -5, 0, +5, +10, +15 D',
      'Hassasiyet': '±0.001 D',
      'Sertifika': 'UME (TÜBİTAK) izlenebilir',
      'Saklama Kutusu': 'Köpük yataklı, kilitli',
      'Aksesuar': 'Mikrofiber bez + temizlik sıvısı',
      'Kalibrasyon Aralığı': '6 ay',
    }),
    techSpecsEN: toSpecs({
      'Lens Count': '6 pieces',
      'Diopter Values': '-10, -5, 0, +5, +10, +15 D',
      'Precision': '±0.001 D',
      'Certificate': 'UME (TÜBİTAK) traceable',
      'Storage Case': 'Foam-padded, lockable',
      'Accessory': 'Microfiber cloth + cleaning fluid',
      'Calibration Interval': '6 months',
    }),
    showPrice: true,
    price: 4500,
    priceCurrency: 'TRY',
    priceNote: '+ KDV, set fiyatıdır',
    monthlyViews: 8,
    isActive: true,
    isFeatured: false,
    isNew: true,
  },
]

// ═══════════════════════════════════════════════════════════
// SERVİSLER (3 adet)
// ═══════════════════════════════════════════════════════════

export const services = [
  {
    _id: 'service-yerinde',
    _type: 'service',
    icon: 'wrench',
    titleTR: 'Yerinde Servis',
    titleEN: 'On-site Service',
    descriptionTR: 'Türkiye geneli teknik müdahale, 24 saat içinde sahaya intikal.',
    descriptionEN: 'Nationwide technical response, on-site within 24 hours.',
    displayOrder: 1,
  },
  {
    _id: 'service-yedek-parca',
    _type: 'service',
    icon: 'box',
    titleTR: 'Orijinal Yedek Parça',
    titleEN: 'Original Spare Parts',
    descriptionTR: 'Kritik parçalarda stoklu temin ve hızlı tedarik.',
    descriptionEN: 'In-stock critical parts and fast procurement.',
    displayOrder: 2,
  },
  {
    _id: 'service-uzaktan-destek',
    _type: 'service',
    icon: 'remote',
    titleTR: 'Uzaktan Destek & Eğitim',
    titleEN: 'Remote Support & Training',
    descriptionTR: 'Online operatör eğitimi ve canlı arıza analizi.',
    descriptionEN: 'Online operator training and live fault analysis.',
    displayOrder: 3,
  },
]

// ═══════════════════════════════════════════════════════════
// NEDEN BİZ (4 adet)
// ═══════════════════════════════════════════════════════════

export const whyUsItems = [
  {
    _id: 'whyus-hassasiyet',
    _type: 'whyUs',
    icon: 'target',
    titleTR: 'Hassasiyet',
    titleEN: 'Precision',
    descriptionTR: '±0.01 mm tekrarlanabilirlik, sahada doğrulanmış.',
    descriptionEN: '±0.01 mm repeatability, field-validated.',
    displayOrder: 1,
  },
  {
    _id: 'whyus-hiz',
    _type: 'whyUs',
    icon: 'bolt',
    titleTR: 'Hız',
    titleEN: 'Throughput',
    descriptionTR: 'Hat tasarımı çevrim süresine göre konfigüre edilir.',
    descriptionEN: 'Line design configured for cycle time targets.',
    displayOrder: 2,
  },
  {
    _id: 'whyus-garanti',
    _type: 'whyUs',
    icon: 'shield',
    titleTR: 'Garanti',
    titleEN: 'Warranty',
    descriptionTR: '24 aya kadar genişletilebilir garanti planı.',
    descriptionEN: 'Extendable warranty plan up to 24 months.',
    displayOrder: 3,
  },
  {
    _id: 'whyus-destek',
    _type: 'whyUs',
    icon: 'head',
    titleTR: '7/24 Destek',
    titleEN: '24/7 Support',
    descriptionTR: 'Uzaktan tanı + 24 saatte yerinde müdahale.',
    descriptionEN: 'Remote diagnostics + 24-hour on-site response.',
    displayOrder: 4,
  },
]

// ═══════════════════════════════════════════════════════════
// İSTATİSTİKLER (4 adet)
// ═══════════════════════════════════════════════════════════

export const stats = [
  {
    _id: 'stat-yil',
    _type: 'stat',
    value: '15+',
    labelTR: 'Yıl tecrübe',
    labelEN: 'Years experience',
    displayOrder: 1,
  },
  {
    _id: 'stat-sistem',
    _type: 'stat',
    value: '200+',
    labelTR: 'Kurulu sistem',
    labelEN: 'Installed systems',
    displayOrder: 2,
  },
  {
    _id: 'stat-hassasiyet',
    _type: 'stat',
    value: '±0.01mm',
    labelTR: 'Hassasiyet',
    labelEN: 'Precision',
    displayOrder: 3,
  },
  {
    _id: 'stat-destek',
    _type: 'stat',
    value: '7/24',
    labelTR: 'Teknik destek',
    labelEN: 'Technical support',
    displayOrder: 4,
  },
]

// ═══════════════════════════════════════════════════════════
// ANA SAYFA (1 doküman — singleton)
// ═══════════════════════════════════════════════════════════

export const homePage = {
  _id: 'homePage',
  _type: 'homePage',
  // Hero
  heroEyebrowTR: 'Optik üretim teknolojileri',
  heroEyebrowEN: 'Optical production technologies',
  heroTitle1TR: 'Optik cam işlemede',
  heroTitle1EN: 'In optical glass processing,',
  heroTitle2TR: 'hassasiyetin mühendisliği',
  heroTitle2EN: 'the engineering of precision',
  heroSubtitleTR: 'Gözlük üreticileri için CNC cam kesim makineleri ve optik ölçüm cihazları — modern üretimin gereksinimleri için tasarlandı.',
  heroSubtitleEN: 'CNC glass cutting machines and optical measurement devices for eyewear manufacturers — designed for the demands of modern production.',
  heroCta1TR: 'Demo Talep Et',
  heroCta1EN: 'Request a Demo',
  heroCta2TR: 'Ürünleri Keşfet',
  heroCta2EN: 'Explore Products',
  heroNoteTR: 'ISO 9001 sertifikalı üretim ortakları',
  heroNoteEN: 'ISO 9001 certified production partners',
  // Video
  videoEyebrowTR: 'Canlı demolar',
  videoEyebrowEN: 'Live demos',
  videoTitleTR: 'Hattınızda gerçek üretim hızında',
  videoTitleEN: 'At real production speed on your line',
  videoSubtitleTR: 'KO-CNC 500X üzerinde 1.8mm CR-39 lens kesimi. Çevrim süresi, sapma toleransı ve kenar kalitesi tek bir ekrandan izlenir.',
  videoSubtitleEN: 'A 1.8mm CR-39 lens cut on the KO-CNC 500X. Cycle time, deviation tolerance and edge quality are monitored on a single screen.',
  videoBulletsTR: [
    'Operatör arayüzü ve ana kontrol panosu',
    'Otomatik kalibrasyon ve değişim rutini',
    'Üretim raporu ve OEE çıktısı',
  ],
  videoBulletsEN: [
    'Operator interface and main control panel',
    'Auto-calibration and changeover routine',
    'Production report and OEE output',
  ],
}

// ═══════════════════════════════════════════════════════════
// SİTE AYARLARI (1 doküman — singleton)
// ═══════════════════════════════════════════════════════════

export const siteSettings = {
  _id: 'siteSettings',
  _type: 'siteSettings',
  // Hakkımızda
  aboutTitleTR: 'Hakkımızda',
  aboutTitleEN: 'About Us',
  aboutContentTR: [
    toBlock('Kahraman Optik, optik cam üretiminde CNC kesim makineleri ve ölçüm cihazları geliştiren bir mühendislik firmasıdır. İstanbul Fatih merkezli üretim tesisimizden Türkiye geneline ve ihracat pazarlarına hizmet veriyoruz.'),
    toBlock('15 yılı aşkın süredir sektörde tasarım ve üretim yapıyoruz. Sahada 200\'den fazla kurulu sistemimiz mevcut; mühendislik ekibimiz, üretim hattınızın gereksinimlerine göre özel konfigürasyon yapmaya devam ediyor.'),
  ],
  aboutContentEN: [
    toBlock('Kahraman Optik is an engineering firm that develops CNC cutting machines and measurement devices for optical glass production. From our Istanbul Fatih production facility, we serve customers across Turkey and export markets.'),
    toBlock('We have been designing and manufacturing in this sector for over 15 years. We currently have more than 200 installed systems in the field; our engineering team continues to customize configurations based on your production line requirements.'),
  ],
  // İletişim
  phone: '+90 539 332 66 66',
  email: 'Kahramansedat@hotmail.com',
  addressTR: 'Şehremini, Ziya Gökalp Sok. 38 A, 34104 Fatih/İstanbul',
  addressEN: 'Şehremini, Ziya Gökalp Sok. 38 A, 34104 Fatih, Istanbul, Turkey',
  workingHoursTR: 'Pazartesi - Cumartesi: 09:00 - 18:00 (Pazar kapalı)',
  workingHoursEN: 'Monday - Saturday: 09:00 - 18:00 (Closed on Sunday)',
  whatsappNumber: '905393326666',
  // Footer
  companyName: 'Kahraman Optik Makine',
  copyrightYear: '2026',
}